inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1

  UseCache: true
  MaxFilesInCache: 20000
  CacheRootDirectory: /tmp

  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
