version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.mge_rails.env
      - ./.secrets.env

    depends_on:
      - mysql
      - solr

  mysql:
    image: mysql:5.6.24
    ports:
      - "3306:3306"
    volumes:
      - mge_data:/var/lib/mysql

  solr:
    image: solr:5.4
    ports:
      - "8983:8983"

volumes:
  mge_data:
    external: true
