web:
  build: .
  ports:
    - "3000:3000"
  env_file:
    - ./mge-rails.env
    - ./secrets.env

  links:
    - db
    - solr

db:
  image: mysql:5.6.24
  ports:
    - "3306:3306"
  env_file:
    - ./mge-rails.env

solr:
  image: solr:5.4
  ports:
    - "8983:8983"
