default: &default
  adapter:  mysql2
  encoding: utf8
  url:      <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['MYSQL_USER_NAME'] %>
  password: <%= ENV['MYSQL_USER_PASSWORD'] %>

development:
  adapter:  mysql2
  encoding: utf8
  host:     <%= ENV['MYSQL_TCP_ADDR'] %>
  username: <%= ENV['MYSQL_USER_NAME'] %>
  password: <%= ENV['MYSQL_USER_PASSWORD'] %>
  database: mge_development

test:
  <<: *default
  database: mge_test

staging:
  <<: *default
  database: mge_staging

production:
  <<: *default
  database: mge_production
